INSERT INTO CONSEJO VALUES (1, 'La paciencia es la clave del éxito.');
INSERT INTO CONSEJO VALUES (2, 'Aprende de tus errores y crece.');
INSERT INTO CONSEJO VALUES (3, 'La perseverancia supera la habilidad.');
INSERT INTO CONSEJO VALUES (4, 'La sabiduría es la verdadera riqueza.');
INSERT INTO CONSEJO VALUES (5, 'El conocimiento es el poder.');
INSERT INTO CONSEJO VALUES (6, 'La gratitud transforma la vida.');
INSERT INTO CONSEJO VALUES (7, 'Sé amable, siempre.');
INSERT INTO CONSEJO VALUES (8, 'La simplicidad es la sofisticación.');
INSERT INTO CONSEJO VALUES (9, 'La educación es la llave del mañana.');
INSERT INTO CONSEJO VALUES (10, 'La curiosidad alimenta la mente.');
INSERT INTO CONSEJO VALUES (11, 'La empatía construye puentes.');
INSERT INTO CONSEJO VALUES (12, 'El respeto es la base de todas las relaciones.');
INSERT INTO CONSEJO VALUES (13, 'La humildad te hará crecer.');
INSERT INTO CONSEJO VALUES (14, 'El tiempo es el recurso más valioso.');
INSERT INTO CONSEJO VALUES (15, 'La creatividad es la madre de la innovación.');
INSERT INTO CONSEJO VALUES (16, 'La vida es un viaje, disfrútalo.');
INSERT INTO CONSEJO VALUES (17, 'El cambio es la única constante.');
INSERT INTO CONSEJO VALUES (18, 'La honestidad es siempre la mejor política.');
INSERT INTO CONSEJO VALUES (19, 'La salud es la verdadera riqueza.');
INSERT INTO CONSEJO VALUES (20, 'Nunca dejes de aprender y crecer.');
INSERT INTO CONSEJO VALUES (21, 'La amistad es un tesoro invaluable.');
INSERT INTO CONSEJO VALUES (22, 'La autenticidad atrae a las personas.');
INSERT INTO CONSEJO VALUES (23, 'La confianza se gana con el tiempo.');
INSERT INTO CONSEJO VALUES (24, 'La planificación es la clave del éxito.');
INSERT INTO CONSEJO VALUES (25, 'El amor y la compasión transforman vidas.');
INSERT INTO CONSEJO VALUES (26, 'La responsabilidad te define como persona.');
INSERT INTO CONSEJO VALUES (27, 'Sé agradecido por las pequeñas cosas.');
INSERT INTO CONSEJO VALUES (28, 'La diversidad enriquece nuestras vidas.');
INSERT INTO CONSEJO VALUES (29, 'La paz interior es un tesoro precioso.');
INSERT INTO CONSEJO VALUES (30, 'La perseverancia supera los obstáculos.');
INSERT INTO CONSEJO VALUES (31, 'La honestidad contigo mismo es esencial.');
INSERT INTO CONSEJO VALUES (32, 'La empatía cura heridas invisibles.');
INSERT INTO CONSEJO VALUES (33, 'Sé el cambio que deseas ver en el mundo.');
INSERT INTO CONSEJO VALUES (34, 'La alegría se encuentra en las pequeñas cosas.');
INSERT INTO CONSEJO VALUES (35, 'La humildad te hace grande.');
INSERT INTO CONSEJO VALUES (36, 'La paciencia es la madre de la sabiduría.');
INSERT INTO CONSEJO VALUES (37, 'La educación es un regalo que perdura.');
INSERT INTO CONSEJO VALUES (38, 'El optimismo ilumina el camino.');
INSERT INTO CONSEJO VALUES (39, 'La honestidad y la integridad van de la mano.');
INSERT INTO CONSEJO VALUES (40, 'La vida es un lienzo en blanco, ¡píntala con amor!');
INSERT INTO CONSEJO VALUES (41, 'La autodisciplina te llevará lejos.');
INSERT INTO CONSEJO VALUES (42, 'La comunicación efectiva es la clave de las relaciones.');
INSERT INTO CONSEJO VALUES (43, 'El conocimiento sin acción es inútil.');
INSERT INTO CONSEJO VALUES (44, 'Sigue tus pasiones y encontrarás tu propósito.');
INSERT INTO CONSEJO VALUES (45, 'La resiliencia te hace invencible.');
INSERT INTO CONSEJO VALUES (46, 'La risa es la mejor medicina.');
INSERT INTO CONSEJO VALUES (47, 'Cuida tu mente, cuerpo y espíritu.');
INSERT INTO CONSEJO VALUES (48, 'Sé valiente y enfrenta tus miedos.');
INSERT INTO CONSEJO VALUES (49, 'La modestia es una virtud subestimada.');
INSERT INTO CONSEJO VALUES (50, 'La paciencia es la clave de la sabiduría.');
INSERT INTO CONSEJO VALUES (51, 'El éxito no tiene atajos.');
INSERT INTO CONSEJO VALUES (52, 'Sé agradecido por tus desafíos, te hacen más fuerte.');
INSERT INTO CONSEJO VALUES (53, 'La empatía es el puente hacia la comprensión.');
INSERT INTO CONSEJO VALUES (54, 'La humildad te acerca a las personas.');
INSERT INTO CONSEJO VALUES (55, 'La perseverancia supera la habilidad.');
INSERT INTO CONSEJO VALUES (56, 'La gratitud es el antídoto contra la insatisfacción.');
INSERT INTO CONSEJO VALUES (57, 'Sé un estudiante de por vida.');
INSERT INTO CONSEJO VALUES (58, 'El respeto es la moneda universal de la humanidad.');
INSERT INTO CONSEJO VALUES (59, 'La felicidad es un viaje, no un destino.');
INSERT INTO CONSEJO VALUES (60, 'El amor es la fuerza más poderosa en el mundo.');
